### ISSUE TITLE
Error with TcpClient

### ISSUE THREAD

**Issue by iGilga** [ru-sh/rabbitmq-dotnet-client#1]
Hi, use this library `RabbitMQ.Client.CoreClrUnofficial 3.6.1.1`. Server rabbitmq on docker with ip `192.168.99.100` on port `5672`.

``` C#
connectionFactory = new ConnectionFactory()
            {
                HostName = "192.168.99.100",
                Port = 5672,
                UserName = "rabbit",
                Password = "rabbit",
                SocketFactory = family =>
                {
                    var tcpClient = new TcpClient(AddressFamily.InterNetwork);
                    return new TcpClientAdapter(tcpClient);
                },
            };
```

Get error message:
`RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.MethodAccessException: Attempt by method 'RabbitMQ.Client.TcpClientAdapter.get_Client()' to access method 'System.Net.Sockets.TcpClient.get_Client()' failed.`

It's problem in .net core?

p.s Using RabbitMQ with version `3.6.2`.

**Comment by ru-sh** [comment]
Hi! Yes. It happened because in RC2 was deleted the TcpClient.Client property.
So this fork works only with RC1.

**Comment by ru-sh** [comment]
I've upload new NuGet package:
https://www.nuget.org/packages/RabbitMQ.Client.CoreClrUnofficial/3.6.1.2-rc2

Use it with caution. I didn't run any tests, so I don't recommend to use it in production.

**Comment by iGilga** [comment]
Hi, it's works, thank you. Yes, .net core too no use it in production.
